site_name: Sunyata
site_url: https://keepsimpler.github.io/sunyata/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Python file: 00_directed_acyclic_graphs.py

plugins:
  # - social
  - search
  - mkdocs-jupyter:
      execute: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/keepsimpler
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/showu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wenfeng-feng-3b874813/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/keepsimpler"  target="_blank" rel="noopener">Wenfeng Feng</a>